### ISSUE TITLE
keras 和 tensorflow版本是多少呢？谢谢

### ISSUE THREAD

**Issue by liuyuan52165** [wotchin/SmooFaceEngine#3]
你好，源代码运行的keras 和 tensorflow版本是多少呢？谢谢

**Comment by wotchin** [comment]
这个比较新的版本应该都可以吧，经测试，使用pip install keras/ tensorflow 安装后的默认版本就可以了。如果还有什么问题，请再反馈即可

**Comment by liuyuan52165** [comment]
王先生，
       您好，非常感谢您的回复，谢谢。请再教您一个问题，我在运行您SmooFaceEngine代码时，训练时有一点问题，报了一个小错，可能因为我是个菜鸟，我做了修改后，训练不报错但是预测出错了。于是想请教您一下，麻烦您了，具体如下：
       
       执行python train.py 时出现如下错误
       
       然后，我删除了如下图所示的amsoftmax.py文件中的红色框圈住的函数，执行python train.py 成功了。然后执行python predit.py报错。

       
祝好
--刘源


------------------ 原始邮件 ------------------
发件人: "Wotchin"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 晚上10:52
收件人: "wotchin/SmooFaceEngine"<SmooFaceEngine@noreply.github.com>;
抄送: "刘源"<1535336333@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wotchin/SmooFaceEngine] keras 和 tensorflow版本是多少呢？谢谢 (#3)




这个比较新的版本应该都可以吧，经测试，使用pip install keras/ tensorflow 安装后的默认版本就可以了。如果还有什么问题，请再反馈即可

**Comment by liuyuan52165** [comment]
好的，非常谢谢您，我成功安装了。同时，运行您的代码的train.py出了点小问题，我尝试解决了两天失败了，这里想请教您一下。（我也发了邮件了，如果您看到这里邮件就不用回复了）谢谢。具体问题如下

**Comment by liuyuan52165** [comment]
Epoch 1/1000
2019-05-14 19:01:03.131038: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
  1/105 [..............................] - ETA: 6:52 - loss: 4.3232 - acc: 0.046  3/105 [..............................] - ETA: 2:17 - loss: 4.3907 - acc: 0.041  5/105 [>.............................] - ETA: 1:22 - loss: 4.2215 - acc: 0.059  7/105 [=>............................] - ETA: 59s - loss: 4.0978 - acc: 0.0670105/105 [==============================] - 9s 82ms/step - loss: 1.7188 - acc: 0.5071 - val_loss: 3.3494 - val_acc: 0.3821

Epoch 00001: loss improved from inf to 1.71878, saving model to ./trained_models/ResNet18.01-0.507143.hdf5
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    validation_steps=int(validation_set_size) / batch_size)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/callbacks.py", line 446, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 83, in _serialize_model
    model_config['config'] = model.get_config()
  File "/home/liuyuan/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 860, in get_config
    layer_config = layer.get_config()
TypeError: 'dict' object is not callable

**Comment by wotchin** [comment]
请将报错Keras的版本号发一下，同时尝试将keras升级至(2.2.4)版本及以上

**Comment by liuyuan52165** [comment]
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> print(keras.__version__)
2.2.4
>>>

**Comment by liuyuan52165** [comment]
您好，安装的是2.24

**Comment by liuyuan52165** [comment]
根据作者本人邮件回复 去掉@properity 即可，谢谢作者大佬

**Comment by wotchin** [comment]
该问题似乎是在使用老旧的keras版本中引入的。
感谢 @liuyuan52165  的勘正，bugfix将在后续提交。
